### PR TITLE
fixed build not working after pr/158 on #137

### PR DESCRIPTION
**Pull request by mwojtera**
When changing English version, other language versions need to be updated as well, when introducing breaking changes, like updating components (Home.vue).

### CODE REVIEW

**Comment by wmcheung** [comment]
My bad would've catched it if I ran build before opening the PR. Would be great to set up a CI build checker in PR's to avoid this in the future

**Comment by mwojtera** [comment]
No worries man. Build checker Action Would be awesome! You think you can whip something up? Sounds like a legit bounty to me.

**Comment by fhilipk** [comment]
Yes we can add that as a bounty.

**Review by fhilipk — APPROVED** [review]

**Comment by wmcheung** [comment]
> > My bad would've catched it if I ran build before opening the PR. Would be great to set up a CI build checker in PR's to avoid this in the future
> 
> No worries man. Build checker Action would be awesome! You think you can whip something up? Sounds like a legit bounty to me.

Sure thing! I'll create an issue

**Pull request merged**
