### PR TITLE
Added support for il8n 

### PR DESCRIPTION
**Pull request by FrancoAra**
Disclaimer: this PR sets up the il8n structure but does not contribute with an actual translation, the few French translations to titles are for proofing the setup is working.

Added support for il8n according Vuepress documentation: https://vuepress.vuejs.org/guide/i18n.html#site-level-i18n-config

This PR copy-pastes the english content into the 'fr' directory and translates some minor titles to show the il8n working. 

To support more languages:

1) edit the /src/.vuepress/config.js file (copy paste the french example and adapt)
1.1) Here is a list of locales to help you find the one you need https://www.science.co.il/language/Locale-codes.php
2) create a language directory inside the /src directory (e.g. '/src/es' for spanish)
3) Copy all english content into the directory
4) Optional: start translating the content inside the language directory

This solves #79 and enables #48

### CODE REVIEW

**Comment by mwojtera** [comment]
There is no point in merging this into main until we have an actual translation present.

**Comment by fhilipk** [comment]
I'm working on one.

**Comment by Cardinense** [comment]
> There is no point in merging this into main until we have an actual translation present.

Hello, I can take care of the Spanish translation. In fact, I have already translated the FAQ.

As it is such a long article, I divided it into two parts. You can find them here: [I Part ](https://forum.cardano.org/t/parte-i-preguntas-frecuentes-sobre-catalyst/55534?u=napoles) and [II Part ](https://forum.cardano.org/t/parte-ii-preguntas-frecuentes-sobre-catalyst/55536?u=napoles)

**Comment by Cardinense** [comment]
> There is no point in merging this into main until we have an actual translation present.

Hello, I can take care of the Spanish translation. In fact, I have already translated the FAQ.

As it is such a long article, I divided it into two parts. You can find them here: [I Part ](https://forum.cardano.org/t/parte-i-preguntas-frecuentes-sobre-catalyst/55534?u=napoles) and [II Part ](https://forum.cardano.org/t/parte-ii-preguntas-frecuentes-sobre-catalyst/55536?u=napoles)

**Comment by FrancoAra** [comment]
It is not uncommon to show the english version while the content gets completely translated, I think there is value to merge this because it igve the structure for others to start contributing part of the translations. It can be done by parts/steps.

Furthermore, I think @fhilipk told me you already had a french translation? you can merge it and then copy/paste the french translation within.

Also I am a developer, my contribution is to enable the translators, if you already have the french translation you can share it with me and I can add it to my PR, but I don't see much value on delaying a functional contribution

**Comment by FrancoAra** [comment]
If you dont agree with me I would like to know what this needs to be merged. I spent part of my busy schedulle to make this contribution and would hate to see it trashed.

**Comment by fhilipk** [comment]
Cardinense would you have this in a doc - we use .md files it's hard to convert HTML to markdown

**Comment by Cardinense** [comment]
https://github.com/Project-Catalyst/project-catalyst.github.io/pull/82#issuecomment-813087222

> Cardinense would you have this in a doc - we use .md files it's hard to convert HTML to markdown

I don't have it in .doc, but I can do it (I'll upload it as soon as I finish, give me a few minutes).... 

However, I would like to learn how to do it by my own means and become a permanent contributor (if there is no problem with that). I am not asking you to invest your time teaching me. Please, I only ask for a link to some content that tells me what I have to read and install to be able to translate the content. The learning and translation into Spanish is on me.

It took me a few hours, but I learned the basics of GitHub enough to install it on my PC along with VS Code, make a fork of this repository, fix some small markdown bugs and make a pool request. I don't know I need to learn something more. I really want to learn.

Regards.

**Comment by mwojtera** [comment]
> If you dont agree with me I would like to know what this needs to be merged. I spent part of my busy schedulle to make this contribution and would hate to see it trashed.

Hi. Sorry for taking some time. Easter is family time and family takes priority. Regarding your work. Thank you for taking the effort, it will not be trashed, it just need some more effort. I don't think it's a good idea to just add a translation of the menu, when we don't have the actual translation. It's like picking up a book with a just translated cover, what will your first reaction be when you see it again? On TownHall or else? Underpromise and overdeliver, otherwise we will lose trust, that's my 3 cents.

@fhilipk If we indeed have a translation, then we need to add a commit with it and move this forward. If it's just a part like with @Cardinense Spanish FAQ, that's fine. Let's just put that into Spanish menu.

@FrancoAra @fhilipk @Cardinense 
I think I have a compromise, regarding translation. 

@FrancoAra Can you add a text in French on top of each page stating that we are looking for a translator and if the proposal gets funded this will be a part of the bounty system?

@Cardinense Could you do the same for Spanish? Minus the FAQ which is translated ofc.

@fhilipk What do you think?

**Comment by mwojtera** [comment]
@Cardinense atm you need a basic knowledge of how to install and use node and npm. After that you need to know how to work with JSON and Markdown.

@FrancoAra has doing translations down so you could ask him if you have any doubts.

**Comment by FrancoAra** [comment]
@mwojtera Thanks for you response, family is priority indeed :) I like the proposed compromise! I will update this hopefully this afternoon.

@Cardinense I can give you a hand with your setup! We can even schedule a 30min live session to help you, search for me at the #master-landing-page Discord channel of the Catalyst Discord. BTW I am a Spanish native speaker, so feel free to speak in Spanish with me as well if you want :)

**Comment by Cardinense** [comment]
@FrancoAra 
> I can give you a hand with your setup! We can even schedule a 30min live session to help you, search for me at the #master-landing-page Discord channel of the Catalyst Discord. BTW I am a Spanish native speaker, so feel free to speak in Spanish with me as well if you want :)

 _I am a Spanish native speaker_
You don't know how glad I am to hear that. That's great! 

_We can even schedule a 30min live session to help you, search for me at the #master-landing-page Discord channel of the Catalyst Discord_
Just tell me when

_I can give you a hand with your setup!_
That's exactly what I need! I would be VERY grateful.

**Comment by fhilipk** [comment]
> That's exactly what I need! I would be VERY grateful.
You can find the discord here: https://discord.gg/HkrCprGHqY

You can start by learning markdown https://www.markdownguide.org/
It's designed so people can create simple content for websites and it's converted into HTML.

There are converter to change doc to markdown (if you search for this you will find) they do a good job but usually need some work or at least a look over to make sure it works.

Thank you so much for helping with this project.

**Comment by FrancoAra** [comment]
@mwojtera @fhilipk @Cardinense I changed the setup from French to Spanish, so to start integrating @Cardinense 's translations. Also I added the "__Estamos buscando traductores, si te interesa contribuir visita [la página de GitHub](https://github.com/Project-Catalyst/project-catalyst.github.io)__" which means "we are looking for translators, if interested visit the Githuib page" to each page

**Comment by FrancoAra** [comment]
As a note, Cardinense and I are in contact, and he is learning really fast!

**Comment by FrancoAra** [comment]
May I request this to be merged and then subsequent fixes/improvements on subsequent PRs?

**Review by mwojtera — APPROVED** [review]

**Comment by FrancoAra** [comment]
yaaay much appreciated! :D

**Pull request merged**
