### PR TITLE
Fund 8 is upon us

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Review by fhilipk — APPROVED** [review]
Thank you for the update :)

**Comment by rodrigc** [comment]
@fhilipk How many people maintain this site?  It would be good to at least keep it up to date with
the latest Catalyst Fund voting information.  
This has no info about the Fund8 timelines for example: https://cardanocataly.st/en/news/

**Comment by rodrigc** [comment]
It might be good to collaborate with @lidonation , since they have a pretty good Catalyst query tool: https://www.lidonation.com/en/project-catalyst/projects
with a good UI, and it looks like it is up to date.

**Comment by fhilipk** [comment]
Hay @rodrigc we're transitioning to the new interface. This was an experiment is community creation that is ongoing. Thank you for your interest. I'm aware of Lidonations work and they have used some data that we have available to create their site. They are also a private business - this sites long term goal is to be community owned and operated. We're not there yet. Keep an eye out for improvements to the UX.

**Comment by fhilipk** [comment]
It's mainly me at this point as we work out a better engagement methodology.

**Pull request merged**
